version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_USER: postgres
      POSTGRES_DB: service_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://db:5432/service_db -user=postgres -password=1234567890 -schemas=service migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

volumes:
  db_data: