services:
  postgres:
    image: postgres:16
    container_name: autoru
    environment:
      POSTGRES_DB: autoru_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rk091011
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10
    container_name: course_flyway
    depends_on:
      - postgres
    command: -connectRetries=60 migrate
    volumes:
      - ./db/migrations:/flyway/sql
      - ./flyway.conf:/flyway/conf/flyway.conf:ro

volumes:
  pgdata: