services:
  db:
    image: postgres:16
    container_name: autoru-db
    environment:
      POSTGRES_DB: autoru_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10
    container_name: autoru-flyway
    depends_on:
      - db
    volumes:
      - ./migrations:/flyway/sql
      - ./flyway.conf:/flyway/conf/flyway.conf
    command: migrate

volumes:
  pgdata:
